name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Find APKs
      run: |
        APK_FILE=$(find app/build/outputs/apk/debug -name '*.apk' | head -n 1)
        echo "APK_FILE=$APK_FILE" >> $GITHUB_ENV
        APK_FILE_NAME=$(basename "$APK_FILE")
        echo "APK_FILE_NAME=$APK_FILE_NAME" >> $GITHUB_ENV

    - name: Upload APKs to Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.APK_FILE_NAME }}
        path: ${{ env.APK_FILE }}
        retention-days: 5
